name: Bug Report
description: File a bug report to help us improve
title: "[BUG]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 
        Please provide as much detail as possible to help us understand and reproduce the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened!
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Run command '...'
        3. See error
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide information about your environment
      placeholder: |
        - OS: [e.g. Ubuntu 20.04, macOS 12.6, Windows 11]
        - Python version: [e.g. 3.9.15]
        - llm-heuristics version: [e.g. 0.1.0]
        - Apptainer version (if applicable): [e.g. 1.2.0]
      value: |
        - OS: 
        - Python version: 
        - llm-heuristics version: 
        - Apptainer version (if applicable): 
    validations:
      required: true

  - type: textarea
    id: dicom-info
    attributes:
      label: DICOM Information (if applicable)
      description: If this is related to DICOM processing, please provide relevant details
      placeholder: |
        - Scanner: [e.g. Siemens Prisma, GE Discovery]
        - Software version: [e.g. syngo MR E11]
        - Sequence types: [e.g. T1w MPRAGE, BOLD EPI]
        - Number of series: [e.g. 15]

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/NeuroHackademy2025/llm-heuristics/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true